/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package app.clientFX.Thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-04-28")
public class Cursa implements org.apache.thrift.TBase<Cursa, Cursa._Fields>, java.io.Serializable, Cloneable, Comparable<Cursa> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Cursa");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DESTINATIE_FIELD_DESC = new org.apache.thrift.protocol.TField("destinatie", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("date", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField LOCURI_DISPONIBILE_FIELD_DESC = new org.apache.thrift.protocol.TField("locuriDisponibile", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CursaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CursaTupleSchemeFactory();

  public int id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String destinatie; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String date; // required
  public int locuriDisponibile; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    DESTINATIE((short)2, "destinatie"),
    DATE((short)3, "date"),
    LOCURI_DISPONIBILE((short)4, "locuriDisponibile");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // DESTINATIE
          return DESTINATIE;
        case 3: // DATE
          return DATE;
        case 4: // LOCURI_DISPONIBILE
          return LOCURI_DISPONIBILE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __LOCURIDISPONIBILE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DESTINATIE, new org.apache.thrift.meta_data.FieldMetaData("destinatie", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATE, new org.apache.thrift.meta_data.FieldMetaData("date", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCURI_DISPONIBILE, new org.apache.thrift.meta_data.FieldMetaData("locuriDisponibile", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Cursa.class, metaDataMap);
  }

  public Cursa() {
  }

  public Cursa(
    int id,
    java.lang.String destinatie,
    java.lang.String date,
    int locuriDisponibile)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.destinatie = destinatie;
    this.date = date;
    this.locuriDisponibile = locuriDisponibile;
    setLocuriDisponibileIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Cursa(Cursa other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetDestinatie()) {
      this.destinatie = other.destinatie;
    }
    if (other.isSetDate()) {
      this.date = other.date;
    }
    this.locuriDisponibile = other.locuriDisponibile;
  }

  public Cursa deepCopy() {
    return new Cursa(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.destinatie = null;
    this.date = null;
    setLocuriDisponibileIsSet(false);
    this.locuriDisponibile = 0;
  }

  public int getId() {
    return this.id;
  }

  public Cursa setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDestinatie() {
    return this.destinatie;
  }

  public Cursa setDestinatie(@org.apache.thrift.annotation.Nullable java.lang.String destinatie) {
    this.destinatie = destinatie;
    return this;
  }

  public void unsetDestinatie() {
    this.destinatie = null;
  }

  /** Returns true if field destinatie is set (has been assigned a value) and false otherwise */
  public boolean isSetDestinatie() {
    return this.destinatie != null;
  }

  public void setDestinatieIsSet(boolean value) {
    if (!value) {
      this.destinatie = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDate() {
    return this.date;
  }

  public Cursa setDate(@org.apache.thrift.annotation.Nullable java.lang.String date) {
    this.date = date;
    return this;
  }

  public void unsetDate() {
    this.date = null;
  }

  /** Returns true if field date is set (has been assigned a value) and false otherwise */
  public boolean isSetDate() {
    return this.date != null;
  }

  public void setDateIsSet(boolean value) {
    if (!value) {
      this.date = null;
    }
  }

  public int getLocuriDisponibile() {
    return this.locuriDisponibile;
  }

  public Cursa setLocuriDisponibile(int locuriDisponibile) {
    this.locuriDisponibile = locuriDisponibile;
    setLocuriDisponibileIsSet(true);
    return this;
  }

  public void unsetLocuriDisponibile() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LOCURIDISPONIBILE_ISSET_ID);
  }

  /** Returns true if field locuriDisponibile is set (has been assigned a value) and false otherwise */
  public boolean isSetLocuriDisponibile() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LOCURIDISPONIBILE_ISSET_ID);
  }

  public void setLocuriDisponibileIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LOCURIDISPONIBILE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case DESTINATIE:
      if (value == null) {
        unsetDestinatie();
      } else {
        setDestinatie((java.lang.String)value);
      }
      break;

    case DATE:
      if (value == null) {
        unsetDate();
      } else {
        setDate((java.lang.String)value);
      }
      break;

    case LOCURI_DISPONIBILE:
      if (value == null) {
        unsetLocuriDisponibile();
      } else {
        setLocuriDisponibile((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case DESTINATIE:
      return getDestinatie();

    case DATE:
      return getDate();

    case LOCURI_DISPONIBILE:
      return getLocuriDisponibile();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case DESTINATIE:
      return isSetDestinatie();
    case DATE:
      return isSetDate();
    case LOCURI_DISPONIBILE:
      return isSetLocuriDisponibile();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Cursa)
      return this.equals((Cursa)that);
    return false;
  }

  public boolean equals(Cursa that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_destinatie = true && this.isSetDestinatie();
    boolean that_present_destinatie = true && that.isSetDestinatie();
    if (this_present_destinatie || that_present_destinatie) {
      if (!(this_present_destinatie && that_present_destinatie))
        return false;
      if (!this.destinatie.equals(that.destinatie))
        return false;
    }

    boolean this_present_date = true && this.isSetDate();
    boolean that_present_date = true && that.isSetDate();
    if (this_present_date || that_present_date) {
      if (!(this_present_date && that_present_date))
        return false;
      if (!this.date.equals(that.date))
        return false;
    }

    boolean this_present_locuriDisponibile = true;
    boolean that_present_locuriDisponibile = true;
    if (this_present_locuriDisponibile || that_present_locuriDisponibile) {
      if (!(this_present_locuriDisponibile && that_present_locuriDisponibile))
        return false;
      if (this.locuriDisponibile != that.locuriDisponibile)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetDestinatie()) ? 131071 : 524287);
    if (isSetDestinatie())
      hashCode = hashCode * 8191 + destinatie.hashCode();

    hashCode = hashCode * 8191 + ((isSetDate()) ? 131071 : 524287);
    if (isSetDate())
      hashCode = hashCode * 8191 + date.hashCode();

    hashCode = hashCode * 8191 + locuriDisponibile;

    return hashCode;
  }

  @Override
  public int compareTo(Cursa other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDestinatie()).compareTo(other.isSetDestinatie());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestinatie()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destinatie, other.destinatie);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDate()).compareTo(other.isSetDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.date, other.date);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLocuriDisponibile()).compareTo(other.isSetLocuriDisponibile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocuriDisponibile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locuriDisponibile, other.locuriDisponibile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Cursa(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("destinatie:");
    if (this.destinatie == null) {
      sb.append("null");
    } else {
      sb.append(this.destinatie);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("date:");
    if (this.date == null) {
      sb.append("null");
    } else {
      sb.append(this.date);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locuriDisponibile:");
    sb.append(this.locuriDisponibile);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CursaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CursaStandardScheme getScheme() {
      return new CursaStandardScheme();
    }
  }

  private static class CursaStandardScheme extends org.apache.thrift.scheme.StandardScheme<Cursa> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Cursa struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESTINATIE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destinatie = iprot.readString();
              struct.setDestinatieIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.date = iprot.readString();
              struct.setDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LOCURI_DISPONIBILE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.locuriDisponibile = iprot.readI32();
              struct.setLocuriDisponibileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Cursa struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.destinatie != null) {
        oprot.writeFieldBegin(DESTINATIE_FIELD_DESC);
        oprot.writeString(struct.destinatie);
        oprot.writeFieldEnd();
      }
      if (struct.date != null) {
        oprot.writeFieldBegin(DATE_FIELD_DESC);
        oprot.writeString(struct.date);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LOCURI_DISPONIBILE_FIELD_DESC);
      oprot.writeI32(struct.locuriDisponibile);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CursaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CursaTupleScheme getScheme() {
      return new CursaTupleScheme();
    }
  }

  private static class CursaTupleScheme extends org.apache.thrift.scheme.TupleScheme<Cursa> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Cursa struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetDestinatie()) {
        optionals.set(1);
      }
      if (struct.isSetDate()) {
        optionals.set(2);
      }
      if (struct.isSetLocuriDisponibile()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetDestinatie()) {
        oprot.writeString(struct.destinatie);
      }
      if (struct.isSetDate()) {
        oprot.writeString(struct.date);
      }
      if (struct.isSetLocuriDisponibile()) {
        oprot.writeI32(struct.locuriDisponibile);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Cursa struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.destinatie = iprot.readString();
        struct.setDestinatieIsSet(true);
      }
      if (incoming.get(2)) {
        struct.date = iprot.readString();
        struct.setDateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.locuriDisponibile = iprot.readI32();
        struct.setLocuriDisponibileIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

