/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package app.clientFX.Thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-04-28")
public class Rezervare implements org.apache.thrift.TBase<Rezervare, Rezervare._Fields>, java.io.Serializable, Cloneable, Comparable<Rezervare> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Rezervare");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ID_CURSA_FIELD_DESC = new org.apache.thrift.protocol.TField("idCursa", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField NR_LOC_FIELD_DESC = new org.apache.thrift.protocol.TField("nrLoc", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField CLIENT_FIELD_DESC = new org.apache.thrift.protocol.TField("client", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RezervareStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RezervareTupleSchemeFactory();

  public int id; // required
  public int idCursa; // required
  public int nrLoc; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String client; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    ID_CURSA((short)2, "idCursa"),
    NR_LOC((short)3, "nrLoc"),
    CLIENT((short)4, "client");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // ID_CURSA
          return ID_CURSA;
        case 3: // NR_LOC
          return NR_LOC;
        case 4: // CLIENT
          return CLIENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __IDCURSA_ISSET_ID = 1;
  private static final int __NRLOC_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ID_CURSA, new org.apache.thrift.meta_data.FieldMetaData("idCursa", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NR_LOC, new org.apache.thrift.meta_data.FieldMetaData("nrLoc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CLIENT, new org.apache.thrift.meta_data.FieldMetaData("client", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Rezervare.class, metaDataMap);
  }

  public Rezervare() {
  }

  public Rezervare(
    int id,
    int idCursa,
    int nrLoc,
    java.lang.String client)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.idCursa = idCursa;
    setIdCursaIsSet(true);
    this.nrLoc = nrLoc;
    setNrLocIsSet(true);
    this.client = client;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Rezervare(Rezervare other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.idCursa = other.idCursa;
    this.nrLoc = other.nrLoc;
    if (other.isSetClient()) {
      this.client = other.client;
    }
  }

  public Rezervare deepCopy() {
    return new Rezervare(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setIdCursaIsSet(false);
    this.idCursa = 0;
    setNrLocIsSet(false);
    this.nrLoc = 0;
    this.client = null;
  }

  public int getId() {
    return this.id;
  }

  public Rezervare setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getIdCursa() {
    return this.idCursa;
  }

  public Rezervare setIdCursa(int idCursa) {
    this.idCursa = idCursa;
    setIdCursaIsSet(true);
    return this;
  }

  public void unsetIdCursa() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IDCURSA_ISSET_ID);
  }

  /** Returns true if field idCursa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdCursa() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IDCURSA_ISSET_ID);
  }

  public void setIdCursaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IDCURSA_ISSET_ID, value);
  }

  public int getNrLoc() {
    return this.nrLoc;
  }

  public Rezervare setNrLoc(int nrLoc) {
    this.nrLoc = nrLoc;
    setNrLocIsSet(true);
    return this;
  }

  public void unsetNrLoc() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NRLOC_ISSET_ID);
  }

  /** Returns true if field nrLoc is set (has been assigned a value) and false otherwise */
  public boolean isSetNrLoc() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NRLOC_ISSET_ID);
  }

  public void setNrLocIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NRLOC_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getClient() {
    return this.client;
  }

  public Rezervare setClient(@org.apache.thrift.annotation.Nullable java.lang.String client) {
    this.client = client;
    return this;
  }

  public void unsetClient() {
    this.client = null;
  }

  /** Returns true if field client is set (has been assigned a value) and false otherwise */
  public boolean isSetClient() {
    return this.client != null;
  }

  public void setClientIsSet(boolean value) {
    if (!value) {
      this.client = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case ID_CURSA:
      if (value == null) {
        unsetIdCursa();
      } else {
        setIdCursa((java.lang.Integer)value);
      }
      break;

    case NR_LOC:
      if (value == null) {
        unsetNrLoc();
      } else {
        setNrLoc((java.lang.Integer)value);
      }
      break;

    case CLIENT:
      if (value == null) {
        unsetClient();
      } else {
        setClient((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case ID_CURSA:
      return getIdCursa();

    case NR_LOC:
      return getNrLoc();

    case CLIENT:
      return getClient();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case ID_CURSA:
      return isSetIdCursa();
    case NR_LOC:
      return isSetNrLoc();
    case CLIENT:
      return isSetClient();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Rezervare)
      return this.equals((Rezervare)that);
    return false;
  }

  public boolean equals(Rezervare that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_idCursa = true;
    boolean that_present_idCursa = true;
    if (this_present_idCursa || that_present_idCursa) {
      if (!(this_present_idCursa && that_present_idCursa))
        return false;
      if (this.idCursa != that.idCursa)
        return false;
    }

    boolean this_present_nrLoc = true;
    boolean that_present_nrLoc = true;
    if (this_present_nrLoc || that_present_nrLoc) {
      if (!(this_present_nrLoc && that_present_nrLoc))
        return false;
      if (this.nrLoc != that.nrLoc)
        return false;
    }

    boolean this_present_client = true && this.isSetClient();
    boolean that_present_client = true && that.isSetClient();
    if (this_present_client || that_present_client) {
      if (!(this_present_client && that_present_client))
        return false;
      if (!this.client.equals(that.client))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + idCursa;

    hashCode = hashCode * 8191 + nrLoc;

    hashCode = hashCode * 8191 + ((isSetClient()) ? 131071 : 524287);
    if (isSetClient())
      hashCode = hashCode * 8191 + client.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Rezervare other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIdCursa()).compareTo(other.isSetIdCursa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdCursa()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idCursa, other.idCursa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNrLoc()).compareTo(other.isSetNrLoc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNrLoc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nrLoc, other.nrLoc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClient()).compareTo(other.isSetClient());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClient()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.client, other.client);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Rezervare(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("idCursa:");
    sb.append(this.idCursa);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nrLoc:");
    sb.append(this.nrLoc);
    first = false;
    if (!first) sb.append(", ");
    sb.append("client:");
    if (this.client == null) {
      sb.append("null");
    } else {
      sb.append(this.client);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RezervareStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RezervareStandardScheme getScheme() {
      return new RezervareStandardScheme();
    }
  }

  private static class RezervareStandardScheme extends org.apache.thrift.scheme.StandardScheme<Rezervare> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Rezervare struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ID_CURSA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.idCursa = iprot.readI32();
              struct.setIdCursaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NR_LOC
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nrLoc = iprot.readI32();
              struct.setNrLocIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CLIENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.client = iprot.readString();
              struct.setClientIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Rezervare struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ID_CURSA_FIELD_DESC);
      oprot.writeI32(struct.idCursa);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NR_LOC_FIELD_DESC);
      oprot.writeI32(struct.nrLoc);
      oprot.writeFieldEnd();
      if (struct.client != null) {
        oprot.writeFieldBegin(CLIENT_FIELD_DESC);
        oprot.writeString(struct.client);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RezervareTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RezervareTupleScheme getScheme() {
      return new RezervareTupleScheme();
    }
  }

  private static class RezervareTupleScheme extends org.apache.thrift.scheme.TupleScheme<Rezervare> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Rezervare struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetIdCursa()) {
        optionals.set(1);
      }
      if (struct.isSetNrLoc()) {
        optionals.set(2);
      }
      if (struct.isSetClient()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetIdCursa()) {
        oprot.writeI32(struct.idCursa);
      }
      if (struct.isSetNrLoc()) {
        oprot.writeI32(struct.nrLoc);
      }
      if (struct.isSetClient()) {
        oprot.writeString(struct.client);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Rezervare struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.idCursa = iprot.readI32();
        struct.setIdCursaIsSet(true);
      }
      if (incoming.get(2)) {
        struct.nrLoc = iprot.readI32();
        struct.setNrLocIsSet(true);
      }
      if (incoming.get(3)) {
        struct.client = iprot.readString();
        struct.setClientIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

