/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Rezervare : TBase
  {
    private int _id;
    private int _idCursa;
    private int _nrLoc;
    private string _client;

    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    public int IdCursa
    {
      get
      {
        return _idCursa;
      }
      set
      {
        __isset.idCursa = true;
        this._idCursa = value;
      }
    }

    public int NrLoc
    {
      get
      {
        return _nrLoc;
      }
      set
      {
        __isset.nrLoc = true;
        this._nrLoc = value;
      }
    }

    public string Client
    {
      get
      {
        return _client;
      }
      set
      {
        __isset.client = true;
        this._client = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool idCursa;
      public bool nrLoc;
      public bool client;
    }

    public Rezervare() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Id = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                IdCursa = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                NrLoc = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Client = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Rezervare");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.id) {
          field.Name = "id";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Id);
          oprot.WriteFieldEnd();
        }
        if (__isset.idCursa) {
          field.Name = "idCursa";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(IdCursa);
          oprot.WriteFieldEnd();
        }
        if (__isset.nrLoc) {
          field.Name = "nrLoc";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(NrLoc);
          oprot.WriteFieldEnd();
        }
        if (Client != null && __isset.client) {
          field.Name = "client";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Client);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Rezervare(");
      bool __first = true;
      if (__isset.id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Id: ");
        __sb.Append(Id);
      }
      if (__isset.idCursa) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IdCursa: ");
        __sb.Append(IdCursa);
      }
      if (__isset.nrLoc) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NrLoc: ");
        __sb.Append(NrLoc);
      }
      if (Client != null && __isset.client) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Client: ");
        __sb.Append(Client);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
